Kmarket_HTML/cs/index.html
=> CS index 페이지 작업중

Kmarket_HTML/admin/index.html
=> index 페이지 수정

Kmarket/.classpath, Kmarket/src/main/java/kr/co/kmarket/controller/admin/IndexController.java, Kmarket/src/main/java/kr/co/kmarket/controller/admin/ProductListController.java, Kmarket/src/main/java/kr/co/kmarket/controller/admin/ProductRegisterController.java, Kmarket/src/main/java/kr/co/kmarket/dao/admin/ArticleDAO.java, Kmarket/src/main/java/kr/co/kmarket/dao/admin/MemberDAO.java, Kmarket/src/main/java/kr/co/kmarket/dao/admin/OrderDAO.java, Kmarket/src/main/java/kr/co/kmarket/dao/admin/ProductDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_Admin.java, Kmarket/src/main/java/kr/co/kmarket/dto/admin/ArticleDTO.java, Kmarket/src/main/java/kr/co/kmarket/dto/admin/MemberDTO.java, Kmarket/src/main/java/kr/co/kmarket/dto/admin/OrderDTO.java, Kmarket/src/main/java/kr/co/kmarket/dto/admin/ProductDTO.java, Kmarket/src/main/java/kr/co/kmarket/service/admin/ArticleService.java, Kmarket/src/main/java/kr/co/kmarket/service/admin/OrderService.java, Kmarket/src/main/java/kr/co/kmarket/service/admin/ProductService.java, Kmarket/src/main/java/kr/co/kmarket/service/admin/UserService.java
=> service dao

Kmarket/src/main/java/kr/co/kmarket/controller/admin/IndexController.java, Kmarket/src/main/java/kr/co/kmarket/controller/admin/ProductListController.java, Kmarket/src/main/java/kr/co/kmarket/controller/admin/ProductRegisterController.java, Kmarket/src/main/java/kr/co/kmarket/dao/admin/OrderDAO.java, Kmarket/src/main/java/kr/co/kmarket/dao/admin/ProductDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_Admin.java, Kmarket/src/main/java/kr/co/kmarket/dto/admin/ProductDTO.java, Kmarket/src/main/java/kr/co/kmarket/service/admin/ProductService.java, Kmarket/src/main/webapp/admin/_footer.jsp, Kmarket/src/main/webapp/admin/_header.jsp, Kmarket/src/main/webapp/admin/index.jsp, Kmarket/src/main/webapp/admin/product/list.jsp, Kmarket/src/main/webapp/admin/product/register.jsp
=> kmarket register

Kmarket/src/main/java/kr/co/kmarket/controller/member/MemberRegisterController.java, Kmarket/src/main/java/kr/co/kmarket/dto/member/Km_memberDTO.java
=> register 수정

Kmarket/src/main/java/kr/co/kmarket/controller/admin/ProductRegisterController.java, Kmarket/src/main/java/kr/co/kmarket/controller/cs/FaqListController.java, Kmarket/src/main/java/kr/co/kmarket/dao/cs/FaqDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_cs.java, Kmarket/src/main/java/kr/co/kmarket/dto/admin/ProductDTO.java, Kmarket/src/main/java/kr/co/kmarket/service/admin/ProductService.java, Kmarket/src/main/java/kr/co/kmarket/service/cs/FaqService.java, Kmarket/src/main/webapp/cs/faq/list.jsp, Kmarket/src/main/webapp/cs/index.jsp, Kmarket2/src/main/java/kr/co/kmarket/dto/cs/FaqDTO.java, Kmarket2/src/main/java/kr/co/kmarket/dto/cs/NoticeDTO.java, Kmarket2/src/main/java/kr/co/kmarket/dto/cs/QnaDTO.java
=> faq list 구현중

Kmarket/.classpath, Kmarket/.settings/org.eclipse.wst.common.project.facet.core.xml, Kmarket/src/main/java/kr/co/kmarket/controller/member/MemberLogoutController.java, Kmarket/src/main/webapp/index.jsp
로그아웃 추가 및 메인 index 페이지 상단 로그인 로그아웃 수정 관리자 추가
=> logout main index 상단수정

Kmarket/src/main/java/kr/co/kmarket/controller/index/IndexController.java, Kmarket/src/main/java/kr/co/kmarket/dao/index/IndexDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_INDEX.java, Kmarket/src/main/java/kr/co/kmarket/service/index/IndexService.java, Kmarket/src/main/webapp/index.jsp, Kmarket/src/main/webapp/member/login.jsp, Kmarket/src/main/webapp/member/register.jsp
인덱스 페이지 작업중
인덱스 컨트롤러 다오 서비스 생성
=> 인덱스페이지 구현중

Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductListController.java, Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductViewController.java, Kmarket/src/main/webapp/product/list.jsp, Kmarket/src/main/webapp/product/view.jsp
product list view 
product controller
=> product list view 데이터작업

Kmarket/src/main/java/kr/co/kmarket/controller/index/IndexController.java, Kmarket/src/main/java/kr/co/kmarket/dao/index/IndexDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_INDEX.java, Kmarket/src/main/java/kr/co/kmarket/service/index/IndexService.java, Kmarket/src/main/webapp/index.jsp
=> hit,score,new,discount 영역구현

Kmarket/src/main/java/kr/co/kmarket/controller/index/IndexController.java, Kmarket/src/main/java/kr/co/kmarket/dao/index/IndexDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_INDEX.java, Kmarket/src/main/java/kr/co/kmarket/service/index/IndexService.java, Kmarket/src/main/webapp/css/common.css, Kmarket/src/main/webapp/index.jsp
=> main index best banner 수정

Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductCartController.java, Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductViewController.java, Kmarket/src/main/java/kr/co/kmarket/dao/product/ProductCartDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_Cart.java, Kmarket/src/main/java/kr/co/kmarket/dto/product/ProductCartDTO.java, Kmarket/src/main/java/kr/co/kmarket/service/product/ProductCartService.java, Kmarket/src/main/webapp/css/common.css, Kmarket/src/main/webapp/index.jsp, Kmarket/src/main/webapp/member/_header.jsp, Kmarket/src/main/webapp/member/login.jsp, Kmarket/src/main/webapp/product/cart.jsp, Kmarket/src/main/webapp/product/header.jsp, Kmarket/src/main/webapp/product/view.jsp
=> 인덱스 약간수정 product 장바구니 insert 및 출력

Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductDeleteController.java, Kmarket/src/main/java/kr/co/kmarket/dao/product/ProductCartDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_Cart.java, Kmarket/src/main/java/kr/co/kmarket/dto/product/ProductCartDTO.java, Kmarket/src/main/webapp/index.jsp, Kmarket/src/main/webapp/product/cart.jsp, Kmarket/src/main/webapp/product/css/main.css
=> 장바구니 기능 구현완료 상품구매하기 구현중

Kmarket/src/main/java/kr/co/kmarket/controller/cs/FaqListController.java, Kmarket/src/main/java/kr/co/kmarket/controller/cs/FaqViewController.java, Kmarket/src/main/java/kr/co/kmarket/dao/cs/ArticleDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_cs.java, Kmarket/src/main/java/kr/co/kmarket/dto/cs/ArticleDTO.java, Kmarket/src/main/java/kr/co/kmarket/service/cs/ArticleService.java, Kmarket/src/main/webapp/cs/_header.jsp, Kmarket/src/main/webapp/cs/faq/list.jsp, Kmarket/src/main/webapp/cs/faq/view.jsp, Kmarket/src/main/webapp/cs/qna/list.jsp, Kmarket/src/main/webapp/cs/qna/view.jsp
=> qna_list 끝

Kmarket/src/main/java/kr/co/kmarket/controller/admin/cs/noticeListController.java, Kmarket/src/main/java/kr/co/kmarket/dao/admin/adminArticleDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_admin.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_cs.java, Kmarket/src/main/java/kr/co/kmarket/dto/admin/adminArticleDTO.java, Kmarket/src/main/java/kr/co/kmarket/service/admin/adminArticleService.java, Kmarket/src/main/webapp/admin/_aside.jsp, Kmarket/src/main/webapp/admin/_header.jsp, Kmarket/src/main/webapp/admin/cs/css/style.css, Kmarket/src/main/webapp/admin/cs/js/listEachCate.js, Kmarket/src/main/webapp/admin/cs/notice/list.jsp, Kmarket/src/main/webapp/admin/cs/notice/view.jsp, Kmarket_HTML/admin/cs/list.html, Kmarket_HTML/admin/cs/view.html, Kmarket_HTML/admin/css/style.css
=> 관리자 공지사항 list완료 view 구현중

Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductCartController.java, Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductDeleteController.java, Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductOrderController.java, Kmarket/src/main/java/kr/co/kmarket/dao/product/ProductCartDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_Cart.java, Kmarket/src/main/java/kr/co/kmarket/dto/product/ProductCartDTO.java, Kmarket/src/main/java/kr/co/kmarket/service/product/ProductCartService.java, Kmarket/src/main/webapp/product/JS/zipcode.js, Kmarket/src/main/webapp/product/cart.jsp, Kmarket/src/main/webapp/product/css/main.css, Kmarket/src/main/webapp/product/header.jsp, Kmarket/src/main/webapp/product/order.jsp
=> 장바구니 구현완료 , 주문하기에서 데이터받아오기완료

Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductCompleteController.java, Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductOrderController.java, Kmarket/src/main/java/kr/co/kmarket/dao/product/ProductCartDAO.java, Kmarket/src/main/java/kr/co/kmarket/dao/product/ProductOrderDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_Cart.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_ORDER.java, Kmarket/src/main/java/kr/co/kmarket/dto/product/ProductItemDTO.java, Kmarket/src/main/java/kr/co/kmarket/dto/product/ProductOrderDTO.java, Kmarket/src/main/java/kr/co/kmarket/service/product/ProductCartService.java, Kmarket/src/main/java/kr/co/kmarket/service/product/ProductOrderService.java, Kmarket/src/main/webapp/index.jsp, Kmarket/src/main/webapp/product/cart.jsp, Kmarket/src/main/webapp/product/complete.jsp, Kmarket/src/main/webapp/product/css/main.css, Kmarket/src/main/webapp/product/order.jsp
=> order 구현완료 complete item,order insert구현완료

Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductListController.java, Kmarket/src/main/java/kr/co/kmarket/dao/product/ProductDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_product.java, Kmarket/src/main/java/kr/co/kmarket/service/product/ProductService.java, Kmarket/src/main/webapp/product/list.jsp, Kmarket/src/main/webapp/product/view.jsp
리스트 뷰 페이지
- 상품 분류
- 페이징
-이미지 크기 조절
=> 프로덕트 리스트 뷰

Kmarket/.classpath, Kmarket/.settings/org.eclipse.wst.common.project.facet.core.xml, Kmarket/src/main/java/kr/co/kmarket/controller/member/MemberLoginController.java, Kmarket/src/main/java/kr/co/kmarket/controller/product/ProductViewController.java, Kmarket/src/main/java/kr/co/kmarket/dao/product/ProductCartDAO.java, Kmarket/src/main/java/kr/co/kmarket/dao/product/ProductDAO.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_Cart.java, Kmarket/src/main/java/kr/co/kmarket/db/SQL_product.java, Kmarket/src/main/java/kr/co/kmarket/filter/CheckLoginFilter.java, Kmarket/src/main/java/kr/co/kmarket/filter/CheckLoginFilter2.java, Kmarket/src/main/java/kr/co/kmarket/service/product/ProductService.java, Kmarket/src/main/webapp/WEB-INF/classes/logback.xml, Kmarket/src/main/webapp/WEB-INF/web.xml, Kmarket/src/main/webapp/css/common.css, Kmarket/src/main/webapp/index.jsp, Kmarket/src/main/webapp/js/timeout.js, Kmarket/src/main/webapp/member/_header.jsp, Kmarket/src/main/webapp/member/login.jsp, Kmarket/src/main/webapp/product/header.jsp, Kmarket/src/main/webapp/product/order.jsp, Kmarket/src/main/webapp/product/view.jsp
=> confirm 및 cart ,order main index수정  filter logback 추가

Kmarket/src/main/java/kr/co/kmarket/controller/cs/board/QnaModifyController.java, Kmarket/src/main/java/kr/co/kmarket/controller/cs/board/QnaWriteController.java, Kmarket/src/main/java/kr/co/kmarket/dao/admin/adminArticleDAO.java, Kmarket/src/main/java/kr/co/kmarket/dto/admin/adminArticleDTO.java, Kmarket/src/main/webapp/admin/cs/css/style.css, Kmarket/src/main/webapp/admin/cs/qna/list.jsp, Kmarket/src/main/webapp/admin/cs/qna/view.jsp, Kmarket/src/main/webapp/admin/cs/qna/write.jsp, Kmarket/src/main/webapp/cs/board/modify.jsp, Kmarket/src/main/webapp/cs/board/qnalist.jsp, Kmarket/src/main/webapp/cs/board/qnawrite.jsp, Kmarket/src/main/webapp/cs/board/view.jsp
=> 전체 삭제가 안되는데 머지 ㅠㅠ 어드민 qna help
